name: mobile_app_function_impl
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  http_parser: ^4.0.0
  mime: ^1.0.4
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5
  intl: ^0.18.1
  image_picker: ^1.0.4
  dio: ^5.3.3
  provider: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/